# Generated by Django 5.1.7 on 2025-03-24 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Medication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("selected_days", models.JSONField()),
                ("dosages", models.JSONField()),
                ("stock", models.IntegerField()),
                ("reminder", models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name="MedicineSchedule",
        ),
    ]
