# Generated by Django 5.1.7 on 2025-04-04 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0002_medication_delete_medicineschedule"),
    ]

    operations = [
        migrations.CreateModel(
            name="DosageSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.CharField(max_length=10)),
                ("time", models.TimeField()),
                ("amount", models.FloatField()),
                (
                    "medication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="schedules.medication",
                    ),
                ),
            ],
        ),
    ]
