# Generated by Django 5.1.7 on 2025-04-14 18:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0004_medication_user_alter_medication_reminder"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="medication",
            options={"ordering": ["user", "dispenser_slot"]},
        ),
        migrations.AddField(
            model_name="medication",
            name="dispenser_slot",
            field=models.PositiveIntegerField(
                blank=True, help_text="User-specific slot ID (1-based index)", null=True
            ),
        ),
        migrations.AddConstraint(
            model_name="medication",
            constraint=models.UniqueConstraint(
                fields=("user", "dispenser_slot"), name="unique_user_dispenser_slot"
            ),
        ),
    ]
