# Generated by Django 5.1.7 on 2025-04-18 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0006_userprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="esp32_ip_address",
            field=models.GenericIPAddressField(
                blank=True, null=True, protocol="IPv4", verbose_name="192.168.1.91"
            ),
        ),
    ]
