# Generated by Django 5.1.7 on 2025-04-19 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0007_alter_userprofile_esp32_ip_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medication",
            name="reminder",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="esp32_ip_address",
            field=models.GenericIPAddressField(
                blank=True,
                default="192.168.1.91",
                null=True,
                protocol="IPv4",
                verbose_name="ESP32 IP Address",
            ),
        ),
        migrations.CreateModel(
            name="MedicationEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("amount", models.FloatField()),
                ("success", models.BooleanField(default=True)),
                ("stock_before", models.IntegerField(blank=True, null=True)),
                ("stock_after", models.IntegerField(blank=True, null=True)),
                ("esp32_response", models.TextField(blank=True, null=True)),
                (
                    "medication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="schedules.medication",
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="schedules.dosageschedule",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
