# Generated by Django 5.1.7 on 2025-04-21 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0008_alter_medication_reminder_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medication",
            name="dispenser_slot",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
