# Generated by Django 5.1.7 on 2025-04-21 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0009_alter_medication_dispenser_slot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medication",
            name="dispenser_slot",
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
