# Generated by Django 5.1.7 on 2025-04-22 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0011_alter_medication_dispenser_slot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="esp32_ip_address",
            field=models.GenericIPAddressField(
                blank=True,
                default="192.168.95.250",
                null=True,
                protocol="IPv4",
                verbose_name="ESP32 IP Address",
            ),
        ),
    ]
