# Generated by Django 4.2.20 on 2025-04-29 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0012_alter_userprofile_esp32_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='esp32_ip_address',
            field=models.GenericIPAddressField(blank=True, default='192.168.1.86', null=True, protocol='IPv4', verbose_name='ESP32 IP Address'),
        ),
    ]
