# Generated by Django 4.2.20 on 2026-03-29 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0013_alter_userprofile_esp32_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='expo_push_token',
            field=models.CharField(blank=True, help_text='Expo push notification token for this user.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='esp32_ip_address',
            field=models.GenericIPAddressField(blank=True, default='192.168.78.250', null=True, protocol='IPv4', verbose_name='ESP32 IP Address'),
        ),
    ]
