# Generated by Django 4.2.20 on 2026-04-01 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0014_userprofile_expo_push_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='device_id',
            field=models.CharField(blank=True, help_text='Unique hardware ID of the physical ESP32 dispenser associated with this user.', max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='esp32_ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, protocol='IPv4', verbose_name='ESP32 IP Address'),
        ),
    ]
